import Head from 'next/head'
import styles from '../styles/Home.module.css'
import A from '../components/A'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <A name="pranav" msg="oklabs"/>
     
    </div>
  )
}
